### ISSUE TITLE
Help me writing idiomatic python

### ISSUE THREAD

**Issue by ape-box** [AtlanticGamingOfficial/AnpaBot#7]

**Comment by makxi007** [comment]
Hi. What do you mean by "Help me writing idiomatic python"?

**Comment by ape-box** [comment]
I'm using this project as hobby to learn python, and I'm conscious a lot of the code is not really pythonic or well structured, so I'm looking for anyone who's willing to give me advice on how to write better python, the right way.

**Comment by makxi007** [comment]
Ok. I thought I can help. But I am also learning python. Good luck!

**Comment by ape-box** [comment]
Thank you @makxi007 if you want to help or just have fun with the bot I'm happy to have a chat, you can come the discord channel, see https://atlanticgaming.altervista.org/.

Most people speak italian, but we can have an english channel to discuss programming, also there might be other people interested in programming ...
